---

  - name: MANAGE ACLS 
    hosts: all 
    connection: network_cli 
    gather_facts: no 

    tasks: 

      - name: Configure ACL on IOSXE 
        ios_config: 
          parents: ip access-list extended INBOUND 
          commands: 
            - permit ip host 172.16.1.1 any log 
            - permit ip host 172.16.2.2 any log 
            - permit ip host 172.16.3.3 any log 

